### ISSUE TITLE
Problem running project on Android

### ISSUE THREAD

**Issue by FrizenVladyslav** [AmitM30/react-native-typescript-boilerplate#6]
Problem running project on Android

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libgnustl_shared.so caused by: dlopen failed: "/data/data/com.fridayapp/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
	at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:917)
	at java.lang.Thread.run(Thread.java:764)

**Comment by a7urag** [comment]
@FrizenVladyslav this issue is related to https://github.com/facebook/react-native/issues/11027
Raised a PR with fixes https://github.com/AmitM30/react-native-typescript-boilerplate/pull/7

**Comment by AmitM30** [comment]
Thanks @a7urag. Also have integrated Travis CI for Android and the [build](https://travis-ci.org/AmitM30/react-native-typescript-boilerplate/builds/486783143?utm_source=github_status&utm_medium=notification) is working fine.

@FrizenVladyslav Please re-open ticket if you are still facing the issue.
